version: "1"
rules:                      # Array of rules
  - base: develp            # Required. Target branch
    upstream: soimort:develp    # Required. Must be in the same fork network. # change `wei` to the owner of upstream repo
    mergeMethod: none  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
